# Generated by Django 5.1.3 on 2025-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bankaccount_bank_name_alter_bankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='lga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='states',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='wards',
            field=models.IntegerField(default=0),
        ),
    ]
