# Generated by Django 5.1.3 on 2025-01-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_statistics_lga_statistics_states_statistics_wards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='lga',
            new_name='lgas',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='villages_reached',
            new_name='villages',
        ),
    ]
