# Generated by Django 5.1.3 on 2025-01-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_aboutministry_created_at_aboutministry_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='people',
            new_name='audiobibles_shared',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='reached',
            new_name='bibles_shared',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='reached_description',
            new_name='people_reached_description',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='people_description',
            new_name='people_saved_description',
        ),
        migrations.RenameField(
            model_name='historicalachievement',
            old_name='people',
            new_name='audiobibles_shared',
        ),
        migrations.RenameField(
            model_name='historicalachievement',
            old_name='reached',
            new_name='bibles_shared',
        ),
        migrations.RenameField(
            model_name='historicalachievement',
            old_name='reached_description',
            new_name='people_reached_description',
        ),
        migrations.RenameField(
            model_name='historicalachievement',
            old_name='people_description',
            new_name='people_saved_description',
        ),
        migrations.AddField(
            model_name='achievement',
            name='audiobibles_description',
            field=models.TextField(default='Audio Bibles shared'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='bibles_shared_description',
            field=models.TextField(default='Bibles were shared'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='lgas_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='lgas_reached_description',
            field=models.TextField(default='Local Governments we have covered'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='people_baptized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='people_baptized_description',
            field=models.TextField(default='People have submitted to Discipleship'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='people_discipled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='people_discipled_description',
            field=models.TextField(default='People have submitted to Discipleship'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='people_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='people_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='sdcard_description',
            field=models.TextField(default='SD cards contain resources were shared'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='sdcards_shared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='started_discipleship',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='started_discipleship_description',
            field=models.TextField(default='People started our Discipleship Program'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='states_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='states_reached_description',
            field=models.TextField(default='States We have covered'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='wards_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='wards_reached_description',
            field=models.TextField(default='Wards we have covered'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='audiobibles_description',
            field=models.TextField(default='Audio Bibles shared'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='bibles_shared_description',
            field=models.TextField(default='Bibles were shared'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='lgas_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='lgas_reached_description',
            field=models.TextField(default='Local Governments we have covered'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='people_baptized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='people_baptized_description',
            field=models.TextField(default='People have submitted to Discipleship'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='people_discipled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='people_discipled_description',
            field=models.TextField(default='People have submitted to Discipleship'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='people_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='people_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='sdcard_description',
            field=models.TextField(default='SD cards contain resources were shared'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='sdcards_shared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='started_discipleship',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='started_discipleship_description',
            field=models.TextField(default='People started our Discipleship Program'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='states_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='states_reached_description',
            field=models.TextField(default='States We have covered'),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='wards_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalachievement',
            name='wards_reached_description',
            field=models.TextField(default='Wards we have covered'),
        ),
    ]
