# Generated by Django 5.1.3 on 2026-04-11 14:55

import django_ckeditor_5.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_people_achievement_audiobibles_shared_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('nav_label', models.CharField(blank=True, help_text='Label shown in navigation (defaults to title)', max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description')),
                ('header_image', models.ImageField(blank=True, help_text='Banner image for the page header', null=True, upload_to='pages/')),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=False, help_text='Add this page to the main navigation bar')),
                ('nav_order', models.IntegerField(default=0, help_text='Sort order in navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
                'ordering': ['nav_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('text', 'Text Block'), ('image_text', 'Image + Text'), ('cards', 'Cards Grid'), ('stats', 'Impact Statistics'), ('cta', 'Call to Action'), ('gallery', 'Image Gallery'), ('video', 'Video Embed'), ('team', 'Team / Board'), ('newsletter', 'Newsletter Signup'), ('map', 'Interactive Map'), ('accordion', 'FAQ / Accordion')], default='text', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/sections/')),
                ('image_position', models.CharField(choices=[('right', 'Image on Right'), ('left', 'Image on Left')], default='right', max_length=10)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=200)),
                ('button2_text', models.CharField(blank=True, max_length=100, verbose_name='Second button text')),
                ('button2_url', models.CharField(blank=True, max_length=200, verbose_name='Second button URL')),
                ('background', models.CharField(choices=[('white', 'White'), ('cream', 'Warm Cream'), ('gray', 'Light Gray'), ('navy', 'Dark Navy'), ('gold', 'Gold'), ('green', 'Forest Green')], default='white', max_length=20)),
                ('css_class', models.CharField(blank=True, help_text='Extra CSS classes', max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('extra_data', models.TextField(blank=True, help_text='JSON data for complex sections. Accordion: [{"question":"...", "answer":"..."}]. Extra stats: [{"number":"...","label":"..."}].')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.page')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageSectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class e.g. fas fa-cross', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/cards/')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.pagesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
