# Generated by Django 5.1.3 on 2026-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_page_pagesection_pagesectioncard'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_header',
            field=models.BooleanField(default=True, help_text='Show the title/banner at the top of the page. Uncheck when the page starts with a Hero section.'),
        ),
    ]
