# Generated by Django 5.2.1 on 2026-04-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_page_show_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, default='Proclaiming the Gospel to unreached people groups across Northern Nigeria since 2006.', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_body',
            field=models.TextField(blank=True, default='Millions remain unreached across Northern Nigeria. Every prayer, every hour of service, every gift — it all moves the needle of eternity.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_heading',
            field=models.CharField(blank=True, default='Be Part of Something Eternal', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalaboutpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, default='Proclaiming the Gospel to unreached people groups across Northern Nigeria since 2006.', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalaboutpage',
            name='cta_body',
            field=models.TextField(blank=True, default='Millions remain unreached across Northern Nigeria. Every prayer, every hour of service, every gift — it all moves the needle of eternity.'),
        ),
        migrations.AddField(
            model_name='historicalaboutpage',
            name='cta_heading',
            field=models.CharField(blank=True, default='Be Part of Something Eternal', max_length=200),
        ),
    ]
