# Generated by Django 5.2.1 on 2026-08-17 14:57

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_activity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('quick', 'Quick Links'), ('involved', 'Get Involved')], default='quick', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='e.g. /about/ or https://example.com', max_length=300)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['column', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Accessible label, e.g. Facebook', max_length=50)),
                ('icon', models.CharField(default='fab fa-facebook-f', help_text='Font Awesome class, e.g. fab fa-facebook-f', max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Social Link',
                'verbose_name_plural': 'Footer Social Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_text', models.TextField(blank=True, default='Reaching unreached people groups across Nigeria with the light and love of Jesus Christ — one village at a time.', help_text='Short paragraph under the footer logo')),
                ('contact_heading', models.CharField(blank=True, default='Contact Us', max_length=100)),
                ('email', models.EmailField(blank=True, default='info@lightoflifeafrica.org', max_length=200)),
                ('phone', models.CharField(blank=True, default='+234 816 480 7904', max_length=50)),
                ('phone_alt', models.CharField(blank=True, help_text='Optional second phone number', max_length=50)),
                ('address', models.CharField(blank=True, default='Northern Nigeria', max_length=255)),
                ('cta_text', models.CharField(blank=True, default='Support Our Mission', max_length=100)),
                ('cta_link', models.CharField(blank=True, default='/give/', max_length=200)),
                ('show_cta', models.BooleanField(default=True)),
                ('quick_links_heading', models.CharField(blank=True, default='Quick Links', max_length=100)),
                ('involved_heading', models.CharField(blank=True, default='Get Involved', max_length=100)),
                ('copyright_text', models.CharField(blank=True, default='Light of Life / HASKE Project. All rights reserved.', help_text="Shown after '© <year>'", max_length=255)),
                ('tagline', models.CharField(blank=True, default="Shining Yahweh's Light, reconciling lives.", max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFooterSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('brand_text', models.TextField(blank=True, default='Reaching unreached people groups across Nigeria with the light and love of Jesus Christ — one village at a time.', help_text='Short paragraph under the footer logo')),
                ('contact_heading', models.CharField(blank=True, default='Contact Us', max_length=100)),
                ('email', models.EmailField(blank=True, default='info@lightoflifeafrica.org', max_length=200)),
                ('phone', models.CharField(blank=True, default='+234 816 480 7904', max_length=50)),
                ('phone_alt', models.CharField(blank=True, help_text='Optional second phone number', max_length=50)),
                ('address', models.CharField(blank=True, default='Northern Nigeria', max_length=255)),
                ('cta_text', models.CharField(blank=True, default='Support Our Mission', max_length=100)),
                ('cta_link', models.CharField(blank=True, default='/give/', max_length=200)),
                ('show_cta', models.BooleanField(default=True)),
                ('quick_links_heading', models.CharField(blank=True, default='Quick Links', max_length=100)),
                ('involved_heading', models.CharField(blank=True, default='Get Involved', max_length=100)),
                ('copyright_text', models.CharField(blank=True, default='Light of Life / HASKE Project. All rights reserved.', help_text="Shown after '© <year>'", max_length=255)),
                ('tagline', models.CharField(blank=True, default="Shining Yahweh's Light, reconciling lives.", max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Footer Settings',
                'verbose_name_plural': 'historical Footer Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
